# Generated by Django 4.0.2 on 2022-02-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='file',
            new_name='download',
        ),
    ]
