# Generated by Django 4.0.3 on 2022-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='id',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号'),
        ),
    ]
