# Generated by Django 4.0.4 on 2022-05-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browseinfo',
            name='machine_uuid',
        ),
    ]
