# Generated by Django 4.0.4 on 2022-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0002_remove_browseinfo_machine_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseinfo',
            name='useragent',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='浏览器的agent信息'),
        ),
    ]
