# Generated by Django 4.0.2 on 2022-03-17 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 9, 6, 17, 357021), verbose_name='验证码过期时间'),
        ),
        migrations.AlterField(
            model_name='phonecode',
            name='phone_num',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
