# Generated by Django 4.0.2 on 2022-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phonecode_exp_date_alter_phonecode_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecode',
            name='exp_date',
        ),
    ]
