# Generated by Django 4.0.2 on 2022-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_form1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='留言时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
