# Generated by Django 4.0.2 on 2022-02-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_form1', '0002_message_create_time_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
    ]
