# Generated by Django 4.0.2 on 2022-02-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_form1', '0003_alter_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='create_time',
        ),
    ]
