# Generated by Django 4.0.2 on 2022-02-16 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_form1', '0004_remove_message_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='留言时间'),
        ),
    ]
