# Generated by Django 4.0.2 on 2022-02-16 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message_form1', '0006_alter_message_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='留言时间'),
        ),
    ]
